"""initial schema level1

Revision ID: 9732cfa9ee05
Revises: 
Create Date: 2026-09-20 17:24:47.107303

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9732cfa9ee05'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='家庭名称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.Enum('family', 'friend', 'work', 'romance', 'other', name='relation_group_enum'), nullable=False, comment='分组'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='正向标签'),
    sa.Column('reverse_name', sa.String(length=50), nullable=True, comment='反向标签'),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False, comment='展示排序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False, comment='所属家庭'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名，小写存储'),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment='展示名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希（bcrypt）'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='停用开关'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_family_id'), 'users', ['family_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tier', sa.Enum('direct', 'edge', name='contact_tier_enum'), server_default='direct', nullable=False, comment='direct 直接联系人 / edge 边缘联系人'),
    sa.Column('last_name', sa.String(length=50), server_default='', nullable=False, comment='姓'),
    sa.Column('first_name', sa.String(length=50), server_default='', nullable=False, comment='名'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='昵称/称呼'),
    sa.Column('display_name_override', sa.String(length=100), nullable=True, comment='手动指定展示名，优先级最高'),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender_enum'), server_default='unknown', nullable=False, comment='性别'),
    sa.Column('organization', sa.String(length=100), nullable=True, comment='单位'),
    sa.Column('bio', sa.Text(), nullable=True, comment='一句话简介'),
    sa.Column('avatar_path', sa.String(length=255), nullable=True, comment='头像路径'),
    sa.Column('status', sa.Enum('active', 'archived', name='contact_status_enum'), server_default='active', nullable=False, comment='active 在册 / archived 归档'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='所有者（创建者），唯一可写'),
    sa.Column('family_id', sa.BigInteger(), nullable=False, comment='所属家庭，服务层保证与所有者一致'),
    sa.Column('visibility', sa.Enum('private', 'family', name='visibility_enum'), server_default='family', nullable=False, comment='可见性：private 私密 / family 家庭可见只读'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='false 表示已归档'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_family_id'), 'contacts', ['family_id'], unique=False)
    op.create_index(op.f('ix_contacts_owner_user_id'), 'contacts', ['owner_user_id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='MCP 工具名'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='工具入参'),
    sa.Column('reason', sa.Text(), nullable=True, comment='agent 提议理由'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'executed', name='pending_status_enum'), server_default='pending', nullable=False, comment='提议状态机'),
    sa.Column('decided_by', sa.BigInteger(), nullable=True, comment='确认人'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='执行结果摘要'),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_family_id'), 'pending_actions', ['family_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='令牌用途，如 Claude Desktop'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='令牌哈希'),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='权限范围，预留'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False, comment='活动标题'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True, comment='地点'),
    sa.Column('detail', sa.Text(), nullable=True, comment='记录详情'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='所有者（创建者），唯一可写'),
    sa.Column('family_id', sa.BigInteger(), nullable=False, comment='所属家庭，服务层保证与所有者一致'),
    sa.Column('visibility', sa.Enum('private', 'family', name='visibility_enum'), server_default='family', nullable=False, comment='可见性：private 私密 / family 家庭可见只读'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='false 表示已归档'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_contact_id'), 'activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_activities_family_id'), 'activities', ['family_id'], unique=False)
    op.create_index(op.f('ix_activities_owner_user_id'), 'activities', ['owner_user_id'], unique=False)
    op.create_table('important_dates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False, comment='所属联系人'),
    sa.Column('type', sa.Enum('birthday', 'anniversary', 'memorial', 'other', name='date_type_enum'), nullable=False, comment='日期类型'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='自定义名称'),
    sa.Column('calendar', sa.Enum('solar', 'lunar', name='calendar_enum'), nullable=False, comment='历法：solar 公历 / lunar 农历'),
    sa.Column('date_solar', sa.Date(), nullable=True, comment='公历日期'),
    sa.Column('lunar_month', sa.SmallInteger(), nullable=True, comment='农历月'),
    sa.Column('lunar_day', sa.SmallInteger(), nullable=True, comment='农历日'),
    sa.Column('lunar_is_leap', sa.Boolean(), server_default='false', nullable=False, comment='是否闰月'),
    sa.Column('yearly', sa.Boolean(), server_default='true', nullable=False, comment='是否每年重复'),
    sa.Column('reminder_lead_days', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='提前提醒天数列表，如 [7,1]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='所有者（创建者），唯一可写'),
    sa.Column('family_id', sa.BigInteger(), nullable=False, comment='所属家庭，服务层保证与所有者一致'),
    sa.Column('visibility', sa.Enum('private', 'family', name='visibility_enum'), server_default='family', nullable=False, comment='可见性：private 私密 / family 家庭可见只读'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_important_dates_contact_id'), 'important_dates', ['contact_id'], unique=False)
    op.create_index(op.f('ix_important_dates_family_id'), 'important_dates', ['family_id'], unique=False)
    op.create_index(op.f('ix_important_dates_owner_user_id'), 'important_dates', ['owner_user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='正文'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='所有者（创建者），唯一可写'),
    sa.Column('family_id', sa.BigInteger(), nullable=False, comment='所属家庭，服务层保证与所有者一致'),
    sa.Column('visibility', sa.Enum('private', 'family', name='visibility_enum'), server_default='family', nullable=False, comment='可见性：private 私密 / family 家庭可见只读'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='false 表示已归档'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_contact_id'), 'notes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_notes_family_id'), 'notes', ['family_id'], unique=False)
    op.create_index(op.f('ix_notes_owner_user_id'), 'notes', ['owner_user_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_contact_id', sa.BigInteger(), nullable=False, comment='主体联系人'),
    sa.Column('to_contact_id', sa.BigInteger(), nullable=False, comment='客体联系人'),
    sa.Column('type_id', sa.BigInteger(), nullable=False, comment='关系类型'),
    sa.Column('note', sa.String(length=200), nullable=True, comment='补充说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='所有者（创建者），唯一可写'),
    sa.Column('family_id', sa.BigInteger(), nullable=False, comment='所属家庭，服务层保证与所有者一致'),
    sa.Column('visibility', sa.Enum('private', 'family', name='visibility_enum'), server_default='family', nullable=False, comment='可见性：private 私密 / family 家庭可见只读'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['from_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['relationship_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_contact_id', 'to_contact_id', 'type_id', name='uq_relation_edge')
    )
    op.create_index(op.f('ix_relationships_family_id'), 'relationships', ['family_id'], unique=False)
    op.create_index(op.f('ix_relationships_from_contact_id'), 'relationships', ['from_contact_id'], unique=False)
    op.create_index(op.f('ix_relationships_owner_user_id'), 'relationships', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_contact_id'), 'relationships', ['to_contact_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详情'),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('todo', 'done', 'cancelled', name='task_status_enum'), server_default='todo', nullable=False, comment='todo / done / cancelled'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False, comment='所有者（创建者），唯一可写'),
    sa.Column('family_id', sa.BigInteger(), nullable=False, comment='所属家庭，服务层保证与所有者一致'),
    sa.Column('visibility', sa.Enum('private', 'family', name='visibility_enum'), server_default='family', nullable=False, comment='可见性：private 私密 / family 家庭可见只读'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_contact_id'), 'tasks', ['contact_id'], unique=False)
    op.create_index(op.f('ix_tasks_family_id'), 'tasks', ['family_id'], unique=False)
    op.create_index(op.f('ix_tasks_owner_user_id'), 'tasks', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_owner_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_family_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_contact_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_relationships_to_contact_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_owner_user_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_contact_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_family_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_notes_owner_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_family_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_contact_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_important_dates_owner_user_id'), table_name='important_dates')
    op.drop_index(op.f('ix_important_dates_family_id'), table_name='important_dates')
    op.drop_index(op.f('ix_important_dates_contact_id'), table_name='important_dates')
    op.drop_table('important_dates')
    op.drop_index(op.f('ix_activities_owner_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_family_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_contact_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_pending_actions_family_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_contacts_owner_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_family_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_family_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('relationship_types')
    op.drop_table('families')
    # ### end Alembic commands ###
